# Site settings
title: Ahmed Elkashef | Supertramp Codes
email: ahmedelkashef2012@gmail.com
url: https://ahmed-elkashef.github.io/
description: "Ahmed Elkashef is a DevOps Engineer and an Ethical Hacker with web development background and over 3 years of experience in a wide range of disciplines and technologies. Constantly in motion, learning and experiencing new things."
keywords: "web-develoepr, information security analyst, CERT, SOC, devops, devsecops, Web, Frontend, Backend, python, javascript, security operations, development operations"
skills: "DevOps Engineer with a FullStack Web Developer background"
meta_author: Elkashef Ahmed

# Google webmaster tools
google_verify: "google4dd33175a0edabac.html"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ahmed Elkashef
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ahmedelkashev
  - title: telegram
    url: https://web.telegram.org/#/im?p=@ahmedelkashev
  - title: stack-overflow
    url: https://stackoverflow.com/users/5896056/ahmed-salah-el-din
  - title: github
    url: https://github.com/Ahmedelkashev
  - title: linkedin
    url: https://www.linkedin.com/in/ahmedelkashef-101

# Postal address (add as many lines as necessary)
address:
  - line: Innopolis, Republic of Tatarstan
  - line: Russian Federation 420500

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
